# Generated by Django 4.2.26 on 2025-11-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_file', models.CharField(help_text='Original CSV file path', max_length=500)),
                ('structure', models.JSONField(default=dict, help_text='Dataset schema definition')),
                ('total_rows', models.IntegerField(default=0)),
                ('total_columns', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('xml_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('xml_schema_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'db_table': 'datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.dataset')),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'db_table': 'import_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DatasetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('decimal', 'Decimal')], max_length=20)),
                ('nullable', models.BooleanField(default=True)),
                ('unique', models.BooleanField(default=False)),
                ('primary_key', models.BooleanField(default=False)),
                ('null_count', models.IntegerField(default=0)),
                ('unique_count', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('sample_values', models.JSONField(default=list, help_text='Sample values from this column')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.dataset')),
            ],
            options={
                'verbose_name': 'Dataset Column',
                'verbose_name_plural': 'Dataset Columns',
                'db_table': 'dataset_columns',
                'ordering': ['dataset', 'position'],
                'unique_together': {('dataset', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Row data as JSON object')),
                ('row_number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.dataset')),
            ],
            options={
                'verbose_name': 'Data Record',
                'verbose_name_plural': 'Data Records',
                'db_table': 'data_records',
                'ordering': ['dataset', 'row_number'],
                'indexes': [models.Index(fields=['dataset', 'row_number'], name='data_record_dataset_461479_idx'), models.Index(fields=['dataset', 'created_at'], name='data_record_dataset_ad8785_idx')],
            },
        ),
    ]
